In [25]:
test1 = open(file="text.txt"
             ,mode="r"
             ,encoding="utf-8"
             ,errors="ignore"
             ,buffering=-1
             ,newline="\n")
print(next(test1))

>QZC44204.1 cytochrome c oxidase subunit I, partial (mitochondrion) [Echinococcus granulosus]

In [23]:
import csv
test2 = csv.reader(open(file="text.csv")
           ,delimiter=","
           ,quotechar='"'
           )
# print(list(test2))
print(next(test2))

['Frame', 'BOND', 'ANGLE', 'DIHED', 'UB', 'IMP', 'CMAP', 'VDWAALS', 'EEL', '1-4 VDW', '1-4 EEL', 'EGB', 'ESURF', 'GGAS', 'GSOLV', 'TOTAL']

In [26]:
test3 = csv.DictReader(open(file="text.csv")
           ,delimiter=","
           ,quotechar='"'
           )
print(next(test3))

{'Frame': '1', 'BOND': '575.97', 'ANGLE': '1313.36', 'DIHED': '1518.97', 'UB': '164.5', 'IMP': '69.25', 'CMAP': '-15.46', 'VDWAALS': '-969.86', 'EEL': '-6509.76', '1-4 VDW': '618.48', '1-4 EEL': '6389.4', 'EGB': '-4321.35', 'ESURF': '102.08', 'GGAS': '3154.84', 'GSOLV': '-4219.27', 'TOTAL': '-1064.43'}

In [57]:
import json
from decimal import Decimal
from numpy import int64
class MyDecoder(json.JSONDecoder):
    def decode(self, s):
        return super().decode(s.replace("\n","").lower())
    
def as_complex(dct):
    if 'complex' in dct:
        dct['complex'] = complex(dct['complex']['real'], dct['complex']['imag'])
        
    return dct

test4 = json.load(open(file="text.json")
                  ,cls=MyDecoder
                  ,object_hook=as_complex
                  ,parse_float=Decimal
                  ,parse_int=int64
                  )
print(test4,type(test4['config']['port']),type(test4['split_ratio']))

{'name': 'project alpha', 'version': '1.0', 'dependencies': ['numpy', 'pandas'], 'config': {'debug': True, 'port': 8080}, 'complex': (3+4j), 'split_ratio': Decimal('0.7')} <class 'numpy.int64'> <class 'decimal.Decimal'>

In [67]:
test5 = json.loads('{"name": "Alice", "age": 30, "is_student": false}'
                  ,cls=MyDecoder
                  ,object_hook=as_complex
                  ,parse_float=Decimal
                  ,parse_int=int64
                  )
print(test5,type(test5['name']),type(test5['age']),type(test5['is_student']))

{'name': 'alice', 'age': 30, 'is_student': False} <class 'str'> <class 'numpy.int64'> <class 'bool'>

In [96]:
import yaml

test6 = yaml.load(open(file="text.yml"), Loader=yaml.SafeLoader)
print(test6, type(test6['age']))

{'name': 'Alice', 'age': 30, 'skills': ['Python', 'YAML', 'Git'], 'languages': ['English', 'Chinese']} <class 'int'>

In [122]:
import xml.etree.ElementTree as ET

test7 = ET.parse(open(file="text.xml"), parser=ET.XMLParser(encoding="utf-8"))
print(test7)
test8 = ET.fromstring(open(file="text.xml").read())
print(test8)
test9 = ET.iterparse(open(file="text.xml"), parser=ET.XMLParser(encoding="utf-8"), events=("end","start"))
for event, elem in test9:
    if event == "end":
        if elem.tag == "year":
            print(f"Processing record: {elem.text}")
            elem.clear()  # 清理已处理的元素
print(test9)

<xml.etree.ElementTree.ElementTree object at 0x000002D95586F2F0>
<Element 'data' at 0x000002D955807740>
Processing record: 2008
Processing record: 2011
<xml.etree.ElementTree.iterparse.<locals>.IterParseIterator object at 0x000002D9569E8410>

In [157]:
from configparser import ConfigParser
test10 = ConfigParser() 
test10.read("text.ini", encoding="utf-8")
print(test10.sections(), test10["DEFAULT"], test10.items("DEFAULT"))

['SEVERE', 'GENERAL', 'logging'] <Section: DEFAULT> [('serveraliveinterval', '45'), ('compression', 'yes')]

In [165]:
import pickle
pk = [1,2.0,"3",4+5j,False, None, {"a":1,"b":2}, (1,2,3),"pwd",[1,2,3]*1000]
pickle.dump(pk, open("text.pkl", "wb"))

buffer = bytearray(100 * 100 * 8)  # 假设数据类型为float64，每个元素8字节
buffers = [memoryview(buffer)]
test11 = pickle.load(open("text.pkl", "rb")
                     ,buffers=buffers
                     )
print(test11)

[1, 2.0, '3', (4+5j), False, None, {'a': 1, 'b': 2}, (1, 2, 3), 'pwd', [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]]

In [177]:
from PIL import Image
test12 = Image.open("img.png", mode="r", formats=["JPEG","JFIF"])
test12.show()

In [315]:
import pandas as pd
test13 = pd.read_csv("text.csv"
                  ,delimiter=","
                  ,header='infer'
                  ,names=None
                  ,index_col=0
                  ,usecols=['Frame','BOND','date','pdb','is_bool','IMP','GGAS']
                  ,dtype={'pdb':str,'is_bool':bool,'BOND':str}
                  ,true_values=['True','1']
                  ,false_values=['False','0']
                  ,skipinitialspace=False
                  ,skiprows=None
                  ,nrows=5
                  ,na_values='a'
                  ,keep_default_na=True
                  ,na_filter=True
                  ,iterator=False
                  ,chunksize=None
                  ,comment=None
                  ,encoding=None
                  ,low_memory=True
                  ,memory_map=False
                  ,skip_blank_lines=True
                  ,parse_dates=['date']
                  ,engine='c'
                  ,converters=None
                  ,dayfirst=False
                  ,cache_dates=True
                  ,compression='infer'
                  ,thousands=None
                  ,decimal='.'
                  ,lineterminator=None
                  ,quotechar='"'
                  ,quoting=0
                  ,doublequote=True
                  ,escapechar=None
                  ,encoding_errors='strict'
                  ,on_bad_lines='error'
                  ,float_precision=None
                  ,storage_options=None
                  )
test13['pdb'].type=str
test13

Frame,BOND,ANGLE,DIHED,is_bool,IMP,1-4 EEL,EGB,ESURF,GGAS,GSOLV,TOTAL,date,pdb
1,575.97,1313.36,1518.97,true,69.25,6389.4,-4321.35,102.08,3154,-4219.27,-1064.43,2025-9-13,a
2,548.49,1323.73,1466.10,False,80.72,6344.46,-4328.80,102.13,3068,-4226.66,-1157.84,2025-9-13,b
3,559.51,1315.62,1488.86,True,73.64,6325.95,-4356.57,101.82,3109,-4254.74,-1145.39,2025-9-13,v
4,529.69,1354.14,1487.21,True,75.57,6333.95,-4396.89,102.55,3187,-4294.34,-1107.02,NaN,f
5,529.72,1313.13,NaN,True,70.78,6365.05,-4340.68,101.20,3082,-4239.48,-1157.33,2025-9-13,c
6,547.65,1294.98,1496.80,False,69.81,6377.27,-4306.24,102.64,3068,-4203.60,-1134.67,2025-9-13,d

In [273]:
import numpy as np
test14 = np.loadtxt("text.csv"
                    ,usecols=[0,1,2]
                    ,skiprows=1
                    ,max_rows=5
                    ,delimiter=","
                    ,dtype=float
                    ,comments=['#','@']
                    ,ndmin=0
                    ,encoding="utf-8"
                    ,unpack=False
                    ,converters={0:lambda x:float(x.replace(" ",""))}
)
test14

array([[1.00000e+00, 5.75970e+02, 1.31336e+03],
       [2.00000e+00, 5.48490e+02, 1.32373e+03],
       [3.00000e+00, 5.59510e+02, 1.31562e+03],
       [4.00000e+00, 5.29690e+02, 1.35414e+03],
       [5.00000e+00, 5.29720e+02, 1.31313e+03]])

In [290]:
np.save('numpy.npy',np.ones((10,8)))
np.savez('numpy.npz',[np.ones((10,8,12)),np.ones((10,8,12))])

test15 = np.load('numpy.npy'
                 ,allow_pickle=True
                 ,mmap_mode=None
                 ,fix_imports=True
                 ,encoding='ASCII'
                 )
test15

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [294]:
test16 = np.load('numpy.npz'
                 ,allow_pickle=True
                 ,mmap_mode=None
                 ,fix_imports=True
                 ,encoding='ASCII'
                 )
list(test16),test16['arr_0']

(['arr_0'],
 array([[[[1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          ...,
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.]],

         [[1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          ...,
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.]],

         [[1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          ...,
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.]],

         ...,

         [[1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          ...,
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.]],

         [[1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          ...,
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.]],

         [[1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          ...,
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.]]],


        [[[1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          ...,
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.]],

         [[1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          ...,
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.]],

         [[1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          ...,
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.]],

         ...,

         [[1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          ...,
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.]],

         [[1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          ...,
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.]],

         [[1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          ...,
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.]]]]))

In [318]:
pd.read_excel("excel.xlsx"
              ,sheet_name="Sheet1"
              ,header=[0,1]
              ,names=None
              ,index_col=0
              ,usecols=None
              ,dtype={'Internal Avg.':float}
              ,engine='openpyxl'
              ,converters=None
              ,true_values=None
              ,false_values=None
              ,skiprows=1
              ,nrows=10
              ,na_values=None
              ,keep_default_na=True
              ,na_filter=True
)

,Avg.,Std. Dev.,Std. Err. of Mean,Avg.,Std. Dev.,Std. Err. of Mean,Avg.,Std. Dev.,Std. Err. of Mean,Avg.,Std. Dev.,Std. Err. of Mean,Avg.,Std. Dev.,Std. Err. of Mean,Avg.,Std. Dev.,Std. Err. of Mean
R:A:CYS:61,0.0,3.083356811879809,0.137754223190136,-5.988023952095924e-05,1.7304728819492583,0.07731182673574018,0.013385229540917375,31.954880814131965,1.4276387885839399,-0.013369261477045924,29.271831018256677,1.3077689639216683,0.0.1,0.3455540662025681,0.015438217132874318,-4.3912175649905044e-05,43.4807489843948,1.9425766025499098
R:A:LEU:62,0.0,3.820237,0.170676,-0.000114,1.496831,0.066873,-0.001852,2.110385,0.094285,0.002349,1.000254,0.044688,0.0,0.130362,0.005824,0.000383,4.722916,0.211004
R:A:LYS:63,0.0,4.183412,0.186901,-0.000138,1.818513,0.081245,0.053864,17.557819,0.784425,-0.053126,16.299995,0.728230,0.0,0.195489,0.008734,0.000601,24.388788,1.089611
R:A:ASN:64,0.0,3.438818,0.153635,-0.000094,1.682649,0.075175,-0.008082,5.587649,0.249638,0.008619,4.832360,0.215894,0.0,0.100505,0.004490,0.000443,8.321082,0.371759

In [336]:
from openpyxl import load_workbook
test17 = load_workbook("excel.xlsx"
                       ,read_only=True
                       ,data_only=False
                       ,keep_vba=False
                       ,keep_links=True
                       )
print(test17, test17.sheetnames, test17['Sheet1'], test17['Sheet1']['W1'].value, test17['Sheet1'].cell(1,1))

<openpyxl.workbook.workbook.Workbook object at 0x000002D960ACCD40> ['Sheet1'] <openpyxl.worksheet._read_only.ReadOnlyWorksheet object at 0x000002D95FFB7320> None <ReadOnlyCell 'Sheet1'.A1>

In [348]:
import xlrd
test18 = xlrd.open_workbook("excel.xls"
                            ,formatting_info=True
                            ,logfile=None
                            ,verbosity=0
                            ,use_mmap=True
                            ,file_contents=None
                            ,encoding_override=None
                            ,on_demand=False
                            ,ragged_rows=False
                            )
test18

In [371]:
import tarfile
test19 = tarfile.open("amber14sb_OL15.ff.tar.gz"
                      ,mode="r"
                      ,fileobj=None
                      ,bufsize=1024
                      ,dereference=False
                      ,ignore_zeros=False
                      ,errorlevel=1
                      ,encoding=None
                      ,pax_headers=None
                      ,debug=0
                      # ,compresslevel=9 #仅用于w:gz, w:bz2
                      )
test19.getnames()

['amber14sb_OL15.ff',
 'amber14sb_OL15.ff/aminoacids.arn',
 'amber14sb_OL15.ff/aminoacids.c.tdb',
 'amber14sb_OL15.ff/aminoacids.hdb',
 'amber14sb_OL15.ff/aminoacids.n.tdb',
 'amber14sb_OL15.ff/aminoacids.r2b',
 'amber14sb_OL15.ff/aminoacids.rtp',
 'amber14sb_OL15.ff/aminoacids.vsd',
 'amber14sb_OL15.ff/atomtypes.atp',
 'amber14sb_OL15.ff/dna.arn',
 'amber14sb_OL15.ff/dna.hdb',
 'amber14sb_OL15.ff/dna.r2b',
 'amber14sb_OL15.ff/dna.rtp',
 'amber14sb_OL15.ff/ffbonded.itp',
 'amber14sb_OL15.ff/ffnonbonded.itp',
 'amber14sb_OL15.ff/forcefield.doc',
 'amber14sb_OL15.ff/forcefield.itp',
 'amber14sb_OL15.ff/gbsa.itp',
 'amber14sb_OL15.ff/ions.itp',
 'amber14sb_OL15.ff/Makefile.am',
 'amber14sb_OL15.ff/Makefile.in',
 'amber14sb_OL15.ff/rna.arn',
 'amber14sb_OL15.ff/rna.hdb',
 'amber14sb_OL15.ff/rna.r2b',
 'amber14sb_OL15.ff/rna.rtp',
 'amber14sb_OL15.ff/spc.itp',
 'amber14sb_OL15.ff/spce.itp',
 'amber14sb_OL15.ff/tip3p.itp',
 'amber14sb_OL15.ff/tip4p.itp',
 'amber14sb_OL15.ff/tip4pew.itp',
 'amber14sb_OL15.ff/tip5p.itp',
 'amber14sb_OL15.ff/urea.itp',
 'amber14sb_OL15.ff/watermodels.dat']

In [377]:
import gzip

with gzip.GzipFile("gzip.gz",mode='wb') as f:
    f.write(b'hello world')

gzip.GzipFile("gzip.gz",mode='rb').read()

b'hello world'

In [ ]:
import zipfile